### ISSUE TITLE
[Idea] Allow setting access token as param on login command

### ISSUE THREAD

**Issue by iMusicJJ** [Orrison/cumulus#2]
Hi,

To run `Cumulus` as part of a deployment CI, and ensure that all domains are up to date, it's way easier to give it the access-key as a param to the main command.

eg:

`cumulus cloudflare:login xxxx`

Rather than `cumulus cloudflare:login` <kbd>enter</kbd> `xxxx`.

**Comment by Orrison** [comment]
Good idea! I can look into making this change sometime soon. You are also welcome to submit a PR with the change as well if you would like.

**Comment by Orrison** [comment]
Howdy @iMusicJJ!

Recently PR #3 we merged in, allowing for the ability to set and consume the Cloudflare API key via `ENV` variable. This should cover the ability to run in CI/CD securely.

The recently cut version `1.1.0` should have this change.

Does this work for you? Or do you still see a use-case for passing in via param?

**Comment by iMusicJJ** [comment]
I am sure that'll work. I'll test it out later! Thanks for the heads up!

**Comment by JapSeyz** [comment]
Sweet, it works like a charm!

Thanks @A-Lawrence & @Orrison
